version: "3.8"

services:
  nginx:
    image: nginx:stable
    container_name: sample-nginx
    ports:
      - "80:80"
    volumes:
        # 後ろの「:ro」で読み取り専用にできる
        - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
#      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - app
    networks:
      - app-net

  app:
    build: ./backend
    container_name: sample-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/appdb?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Tokyo
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: app_pass
    volumes:
      - ./backend/build/libs/sample_bbs-1.0.jar:/app/app.jar:ro
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-net

  mysql:
    image: mysql:9.6.0
    container_name: sample-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
      TZ: Asia/Tokyo
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/my.conf:/etc/mysql/conf.d/my.cnf:ro
    ports:
      - "3306:3306"
    networks:
      - app-net

networks:
  app-net:

volumes:
  mysql-data: